// <auto-generated />
namespace LifeSongComposers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatedtrackclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedtrackclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201806242114200_updated track class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
